configInline:
  address-pools:
   - name: external-pool
     protocol: layer2
     addresses:
     - 10.50.0.64/26
     auto-assign: true
   - name: static-pool
     protocol: layer2
     addresses:
     - 10.50.0.32/27
     auto-assign: false
     
