grafana.ini:
  server:
    domain: grafana.example.com
    serve_from_sub_path: false
ingress:
  enabled: true
  annotations:
    metallb.universe.tf/address-pool: external-pool
    external-dns.alpha.kubernetes.io/hostname: grafana.sour.ninja
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - "grafana.sour.ninja"
  tls:
    - secretName: grafana-certificate
      hosts:
        - grafana.sour.ninja
admin:
  existingSecret: grafana-admin-creds

persistence:
  enabled: true
